/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LegalContent {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'author' : Nickname,
}
export interface PaymentConfirmation {
  'nickname' : Nickname,
  'transactionHash' : string,
  'submittedAt' : Time,
  'approved' : boolean,
}
export type Nickname = string;
export type PasswordHash = string;
export interface Profile { 'nickname' : Nickname, 'password' : PasswordHash }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<[Profile, PasswordHash], undefined>,
  'getAllLegalContent' : ActorMethod<[], Array<LegalContent>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLegalContentById' : ActorMethod<[bigint], [] | [LegalContent]>,
  'getMemberContent' : ActorMethod<[], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, PasswordHash], boolean>,
  'register' : ActorMethod<[string, PasswordHash], undefined>,
  'submitPaymentConfirmation' : ActorMethod<[string, string], undefined>,
  'getPaymentConfirmations' : ActorMethod<[], Array<PaymentConfirmation>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
