/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Nickname = IDL.Text;
export const PasswordHash = IDL.Text;
export const Profile = IDL.Record({
  'nickname' : Nickname,
  'password' : PasswordHash,
});
export const Time = IDL.Int;
export const LegalContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'author' : Nickname,
});
export const PaymentConfirmation = IDL.Record({
  'nickname' : Nickname,
  'transactionHash' : IDL.Text,
  'cryptocurrency' : IDL.Text,
  'submittedAt' : Time,
  'approved' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePassword' : IDL.Func([Profile, PasswordHash], [], []),
  'getAllLegalContent' : IDL.Func([], [IDL.Vec(LegalContent)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLegalContentById' : IDL.Func([IDL.Nat], [IDL.Opt(LegalContent)], ['query']),
  'getMemberContent' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, PasswordHash], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, PasswordHash], [], []),
  'submitPaymentConfirmation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getPaymentConfirmations' : IDL.Func([], [IDL.Vec(PaymentConfirmation)], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Nickname = IDL.Text;
  const PasswordHash = IDL.Text;
  const Profile = IDL.Record({
    'nickname' : Nickname,
    'password' : PasswordHash,
  });
  const Time = IDL.Int;
  const LegalContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'author' : Nickname,
  });
  const PaymentConfirmation = IDL.Record({
    'nickname' : Nickname,
    'transactionHash' : IDL.Text,
    'cryptocurrency' : IDL.Text,
    'submittedAt' : Time,
    'approved' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePassword' : IDL.Func([Profile, PasswordHash], [], []),
    'getAllLegalContent' : IDL.Func([], [IDL.Vec(LegalContent)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLegalContentById' : IDL.Func([IDL.Nat], [IDL.Opt(LegalContent)], ['query']),
    'getMemberContent' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, PasswordHash], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, PasswordHash], [], []),
    'submitPaymentConfirmation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getPaymentConfirmations' : IDL.Func([], [IDL.Vec(PaymentConfirmation)], ['query']),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
